spring:
  application:
    name: phoneNumber-service
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: jdbc:postgresql://db:5432/phone_db
    username: robot
    password: robotpass

server:
  port : 9997
